version: '3.7'

services:

  db:
    image: postgres:9.6
    restart: always
    env_file:
      ./App/config/.db_config
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: DB1
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  worker:
    tty: true
    restart: always
    build:
      context: .
      network: host
    depends_on:
      - db
    env_file:
      ./App/config/.worker_config
    volumes:
      - ${WORKER_SRC}:/mnt/FromRetinal

  scheduler:
    image: mcuadros/ofelia:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./App/config/scheduler.ini:/etc/ofelia/config.yml
    depends_on:
      - db
      - worker
    restart: always
