version: '3.7'

services:
  worker:
    tty: true
    restart: always
    build:
      context: .
      network: host
    env_file:
      ./App/config/.worker_config
    volumes:
      - ${WORKER_SRC}:/mnt/FromRetinal

  scheduler:
    image: mcuadros/ofelia:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./App/config/scheduler.ini:/etc/ofelia/config.yml
    depends_on:
      - worker
    restart: always
