version: '3.7'

services:

  single_db:
    image: postgres:9.6
    restart: always
    env_file:
      ./.env-docker
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: DB1
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'




